spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true

  shell:
    interactive:
      enabled: true

  banner:
    # Файл баннера
    location: banner.txt

  output:
    ansi:
      # Цветной вывод в консоль
      enabled: ALWAYS

logging:
  level:
    ru:
      diasoft:
        ncheranev:
          otus: debug
